export interface Session { access_token: string; org_id: string; role: string; name: string; }
export interface Org { id: string; name: string; slug: string; vertical: string; primary_color: string; baseline_response_s: number; }
export interface Device { id: string; name: string; external_id: string; lat: number; lon: number; status: string; battery: number | null; rssi: number | null; tags: string[]; last_seen: string | null; }
export interface AlertSource { source_type: string; ref_id: string | null; weight: number; detail: Record<string, unknown> | null; }
export interface Alert { id: string; type: string; severity: string; status: string; lat: number; lon: number; confidence: number; title: string; detected_at: string; acknowledged_at: string | null; resolved_at: string | null; sources: AlertSource[]; }
export interface Detection { id: string; source: string; lat: number; lon: number; brightness: number | null; confidence: number | null; frp: number | null; acquired_at: string; }
export interface Report { id: string; type: string; description: string | null; photo_url: string | null; lat: number; lon: number; status: string; correlation_score: number | null; reputation_score: number | null; created_at: string; }
export interface Kpi { detection_time_s: number | null; detection_target_s: number; model_precision: number | null; precision_target: number; valid_reports_rate: number | null; valid_reports_target: number; response_time_reduction: number | null; response_reduction_target: number; global_status: "normal" | "atencion" | "critico"; active_alerts: number; }
export interface Rule { id: string; name: string; alert_type: string; conditions: {variable:string;operator:string;threshold:number}[]; condition_logic: string; window_seconds: number; severity: string; require_satellite: boolean; enabled: boolean; }
