export type MisionesMunicipality = { name: string; department: string };

export const MISIONES_CENTER = { latitude: -26.92, longitude: -54.78 };
export const MISIONES_BOUNDS = { south: -28.20, west: -56.10, north: -25.45, east: -53.55 };
export const MISIONES_MUNICIPALITIES: MisionesMunicipality[] = [
  { name: "Apóstoles", department: "Apóstoles" },
  { name: "Azara", department: "Apóstoles" },
  { name: "San José", department: "Apóstoles" },
  { name: "Tres Capones", department: "Apóstoles" },
  { name: "Aristóbulo del Valle", department: "Cainguás" },
  { name: "Campo Grande", department: "Cainguás" },
  { name: "Dos de Mayo", department: "Cainguás" },
  { name: "Salto Encantado", department: "Cainguás" },
  { name: "Bonpland", department: "Candelaria" },
  { name: "Candelaria", department: "Candelaria" },
  { name: "Cerro Corá", department: "Candelaria" },
  { name: "Loreto", department: "Candelaria" },
  { name: "Mártires", department: "Candelaria" },
  { name: "Profundidad", department: "Candelaria" },
  { name: "Santa Ana", department: "Candelaria" },
  { name: "Fachinal", department: "Capital" },
  { name: "Garupá", department: "Capital" },
  { name: "Posadas", department: "Capital" },
  { name: "Concepción de la Sierra", department: "Concepción" },
  { name: "Santa María", department: "Concepción" },
  { name: "9 de Julio", department: "Eldorado" },
  { name: "Colonia Delicia", department: "Eldorado" },
  { name: "Colonia Victoria", department: "Eldorado" },
  { name: "Eldorado", department: "Eldorado" },
  { name: "Santiago de Liniers", department: "Eldorado" },
  { name: "Bernardo de Irigoyen", department: "General Manuel Belgrano" },
  { name: "Comandante Andresito", department: "General Manuel Belgrano" },
  { name: "Dos Hermanas", department: "General Manuel Belgrano" },
  { name: "San Antonio", department: "General Manuel Belgrano" },
  { name: "El Soberbio", department: "Guaraní" },
  { name: "Fracrán", department: "Guaraní" },
  { name: "San Vicente", department: "Guaraní" },
  { name: "Puerto Esperanza", department: "Iguazú" },
  { name: "Puerto Iguazú", department: "Iguazú" },
  { name: "Puerto Libertad", department: "Iguazú" },
  { name: "Wanda", department: "Iguazú" },
  { name: "Almafuerte", department: "Leandro N. Alem" },
  { name: "Arroyo del Medio", department: "Leandro N. Alem" },
  { name: "Caá Yarí", department: "Leandro N. Alem" },
  { name: "Cerro Azul", department: "Leandro N. Alem" },
  { name: "Dos Arroyos", department: "Leandro N. Alem" },
  { name: "Gobernador López", department: "Leandro N. Alem" },
  { name: "Leandro N. Alem", department: "Leandro N. Alem" },
  { name: "Olegario Víctor Andrade", department: "Leandro N. Alem" },
  { name: "Capioví", department: "Libertador General San Martín" },
  { name: "El Alcázar", department: "Libertador General San Martín" },
  { name: "Garuhapé", department: "Libertador General San Martín" },
  { name: "Puerto Leoni", department: "Libertador General San Martín" },
  { name: "Puerto Rico", department: "Libertador General San Martín" },
  { name: "Ruiz de Montoya", department: "Libertador General San Martín" },
  { name: "Caraguatay", department: "Montecarlo" },
  { name: "Montecarlo", department: "Montecarlo" },
  { name: "Puerto Piray", department: "Montecarlo" },
  { name: "Campo Ramón", department: "Oberá" },
  { name: "Campo Viera", department: "Oberá" },
  { name: "Colonia Alberdi", department: "Oberá" },
  { name: "General Alvear", department: "Oberá" },
  { name: "Guaraní", department: "Oberá" },
  { name: "Los Helechos", department: "Oberá" },
  { name: "Oberá", department: "Oberá" },
  { name: "Panambí", department: "Oberá" },
  { name: "San Martín", department: "Oberá" },
  { name: "Colonia Polana", department: "San Ignacio" },
  { name: "Corpus Christi", department: "San Ignacio" },
  { name: "General Urquiza", department: "San Ignacio" },
  { name: "Gobernador Roca", department: "San Ignacio" },
  { name: "Hipólito Yrigoyen", department: "San Ignacio" },
  { name: "Jardín América", department: "San Ignacio" },
  { name: "San Ignacio", department: "San Ignacio" },
  { name: "Santo Pipó", department: "San Ignacio" },
  { name: "Florentino Ameghino", department: "San Javier" },
  { name: "Itacaruaré", department: "San Javier" },
  { name: "Mojón Grande", department: "San Javier" },
  { name: "San Javier", department: "San Javier" },
  { name: "Pozo Azul", department: "San Pedro" },
  { name: "San Pedro", department: "San Pedro" },
  { name: "25 de Mayo", department: "25 de Mayo" },
  { name: "Alba Posse", department: "25 de Mayo" },
  { name: "Colonia Aurora", department: "25 de Mayo" },
];

export function municipalityDepartment(name: string): string | null {
  return MISIONES_MUNICIPALITIES.find((item) => item.name === name)?.department || null;
}

export function isInMisiones(latitude: number, longitude: number): boolean {
  return Number.isFinite(latitude) && Number.isFinite(longitude)
    && latitude >= MISIONES_BOUNDS.south && latitude <= MISIONES_BOUNDS.north
    && longitude >= MISIONES_BOUNDS.west && longitude <= MISIONES_BOUNDS.east;
}
