import { LegalPage, LegalSection, legalContact, legalEntity } from "../../components/LegalPage";

export default function PrivacyPage() {
  return <LegalPage title="Política de Privacidad" subtitle="Cómo EcoNexo recopila, usa, protege y elimina datos personales.">
    <LegalSection number="01" title="Responsable y alcance"><p>Responsable propuesto: <strong>{legalEntity.name}</strong>, CUIT <strong>{legalEntity.cuit}</strong>, domicilio <strong>{legalEntity.address}</strong>. Esta política alcanza a la plataforma web, el centro de comando, informes compartidos y el canal de reportes ciudadanos. Debe complementarse con los contratos de cada organización, que pueden asignar roles de responsable y encargado de tratamiento.</p></LegalSection>
    <LegalSection number="02" title="Datos tratados"><div className="legal-table"><div><strong>Cuenta y Google</strong><span>Nombre, email verificado, identificador estable de Google, imagen de perfil, organización, rol y aceptación legal.</span></div><div><strong>Operación</strong><span>Eventos, acciones, reglas, dispositivos, telemetría, zonas, alertas, registros técnicos, IP aproximada y trazabilidad.</span></div><div><strong>Reporte ciudadano</strong><span>Tipo, descripción, fotografía opcional, coordenadas, fecha, token seudónimo, correlación y resultado de moderación.</span></div><div><strong>Informes compartidos</strong><span>Destinatario, período, métricas, hallazgos, recomendaciones, token de enlace y fecha de publicación.</span></div></div><p>Las fotografías y la geolocalización pueden identificar directa o indirectamente a una persona; deben enviarse sólo cuando resulten pertinentes.</p></LegalSection>
    <LegalSection number="03" title="Finalidades"><ul><li>Autenticar usuarios, administrar organizaciones y aplicar permisos.</li><li>Operar, correlacionar y visualizar información ambiental y territorial.</li><li>Recibir, moderar y prevenir abuso en reportes ciudadanos.</li><li>Generar informes, enlaces revocables, métricas y trazabilidad.</li><li>Proteger la plataforma, investigar incidentes, mantener respaldos y cumplir obligaciones legales.</li><li>Mejorar modelos y funciones únicamente con datos agregados, anonimizados o bajo acuerdo específico.</li></ul></LegalSection>
    <LegalSection number="04" title="Bases de legitimación"><p>Según el caso, el tratamiento se apoya en consentimiento informado, ejecución de contrato, interés legítimo sujeto a evaluación, cumplimiento de obligaciones legales o ejercicio de funciones públicas por la organización cliente. El consentimiento puede retirarse sin afectar tratamientos previos lícitos. No se reutilizarán datos para fines incompatibles sin una nueva base legal.</p></LegalSection>
    <LegalSection number="05" title="Destinatarios y proveedores"><p>Los datos pueden ser procesados por proveedores de infraestructura, almacenamiento, autenticación, mapas, mensajería, observación terrestre, soporte y seguridad, bajo contratos y acceso mínimo. Google procesa el inicio de sesión conforme a sus políticas. La organización destinataria accede a los reportes dirigidos a su territorio. No vendemos datos personales ni los usamos para publicidad comportamental.</p></LegalSection>
    <LegalSection number="06" title="Transferencias internacionales"><p>Algunos proveedores pueden procesar información fuera de Argentina. Antes de producción se documentarán países, proveedores, garantías contractuales y evaluaciones aplicables. Cuando corresponda se utilizarán cláusulas contractuales, jurisdicciones adecuadas u otros mecanismos reconocidos por la autoridad competente.</p></LegalSection>
    <LegalSection number="07" title="Conservación"><div className="legal-table"><div><strong>Cuenta</strong><span>Mientras permanezca activa y hasta 2 años posteriores, salvo obligación o acuerdo distinto.</span></div><div><strong>Registros de seguridad</strong><span>12 a 24 meses, según criticidad e investigación.</span></div><div><strong>Reportes y evidencia</strong><span>Plazo definido por la organización; propuesta inicial de 24 meses con revisión periódica.</span></div><div><strong>Enlaces públicos</strong><span>Hasta revocación o vencimiento contractual; el token se almacena únicamente como hash.</span></div><div><strong>Respaldos</strong><span>Ciclo controlado de hasta 90 días tras eliminación lógica.</span></div></div><p>Estos plazos son parámetros de diseño y deben ajustarse por contrato, normativa sectorial y finalidad.</p></LegalSection>
    <LegalSection number="08" title="Seguridad"><p>Se aplican separación por organización, roles, autenticación, tokens firmados, secretos fuera del código, cifrado en tránsito, almacenamiento privado de imágenes, enlaces temporales, credenciales internas entre servicios, límites de uso, validación de archivos, auditoría y respaldos. Ninguna medida elimina todo riesgo; existe un proceso de respuesta y notificación de incidentes.</p></LegalSection>
    <LegalSection number="09" title="Derechos"><p>Las personas pueden solicitar acceso, rectificación, actualización, supresión, retiro del consentimiento y demás derechos previstos por la Ley argentina 25.326. La solicitud debe enviarse a <strong>{legalContact}</strong> con información suficiente para verificar identidad y localizar los datos. También puede acudirse a la Agencia de Acceso a la Información Pública, autoridad de control en Argentina.</p></LegalSection>
    <LegalSection number="10" title="Menores y datos sensibles"><p>El servicio no está dirigido a menores para crear cuentas institucionales. Los reportes ciudadanos no deben incluir deliberadamente datos sensibles, rostros identificables, patentes, documentos ni información de salud salvo necesidad legítima, proporcional y autorizada. Se aplicarán mecanismos de minimización o retiro cuando corresponda.</p></LegalSection>
    <LegalSection number="11" title="Decisiones automatizadas"><p>Los puntajes de correlación y reputación priorizan revisión, pero no deben producir por sí solos sanciones, denuncias ni efectos jurídicos significativos. La moderación y la respuesta requieren intervención humana, contexto y posibilidad de revisión.</p></LegalSection>
    <LegalSection number="12" title="Cambios y contacto"><p>Las versiones materiales se comunicarán y mostrarán con fecha de vigencia. Consultas, derechos o incidentes de privacidad: <strong>{legalContact}</strong>.</p></LegalSection>
  </LegalPage>;
}
