apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: api-pdb, namespace: econexo }
spec:
  minAvailable: 1
  selector: { matchLabels: { app: api } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: web-pdb, namespace: econexo }
spec:
  minAvailable: 1
  selector: { matchLabels: { app: web } }
