import { LegalPage, LegalSection, legalContact, legalEntity } from "../../components/LegalPage";

export default function TermsPage() {
  return <LegalPage title="Términos y Condiciones" subtitle="Reglas de acceso, uso responsable y alcance del servicio EcoNexo.">
    <LegalSection number="01" title="Identificación y aceptación"><p>EcoNexo es una plataforma tecnológica operada por <strong>{legalEntity.name}</strong>, CUIT <strong>{legalEntity.cuit}</strong>, con domicilio en <strong>{legalEntity.address}</strong> (el “Proveedor”). Al crear una cuenta, aceptar estos términos o utilizar la plataforma, la persona usuaria y la organización que representa aceptan este acuerdo y declaran tener capacidad y autorización suficientes.</p></LegalSection>
    <LegalSection number="02" title="Objeto del servicio"><p>La plataforma integra telemetría IoT, fuentes satelitales, datos meteorológicos, reportes ciudadanos y reglas configurables para apoyar la detección, priorización, documentación y comunicación de incidentes ambientales. Las funciones disponibles pueden variar según el plan, la región, las integraciones y el contrato particular.</p><div className="legal-alert"><strong>EcoNexo no es un servicio de emergencias.</strong> Las alertas son apoyo a la decisión y no sustituyen protocolos oficiales, inspecciones, peritajes, certificaciones, avisos regulatorios ni comunicaciones a organismos de respuesta.</div></LegalSection>
    <LegalSection number="03" title="Cuentas, Google y roles"><p>El acceso puede realizarse mediante Google Identity Services o credenciales locales. La organización es responsable de mantener actualizados sus administradores, asignar roles con mínimo privilegio, retirar accesos cuando corresponda y notificar incidentes. EcoNexo no recibe la contraseña de Google. El primer usuario que registra una nueva organización mediante Google se asigna como administrador, sujeto a verificación contractual posterior.</p></LegalSection>
    <LegalSection number="04" title="Obligaciones de uso"><ul><li>Ingresar información lícita, exacta y pertinente para la finalidad ambiental u operativa declarada.</li><li>No intentar eludir controles, acceder a otra organización, interferir con la plataforma, introducir código malicioso ni realizar pruebas de seguridad sin autorización escrita.</li><li>No utilizar EcoNexo para vigilancia ilegal, discriminación, persecución, perfilado indebido ni decisiones exclusivamente automatizadas que produzcan efectos jurídicos significativos.</li><li>Contar con bases legales, permisos y cartelería aplicables para sensores, cámaras, geolocalización, imágenes, contactos y comunicaciones.</li></ul></LegalSection>
    <LegalSection number="05" title="Reportes, imágenes y contenido"><p>Quien envía contenido declara que lo obtuvo y comparte legítimamente, que actúa de buena fe y que no vulnera derechos de terceros. Conserva sus derechos sobre el contenido y otorga al Proveedor una licencia limitada, no exclusiva y revocable según los plazos de retención, únicamente para alojar, procesar, correlacionar, mostrar y respaldar el reporte dentro de la finalidad del servicio.</p></LegalSection>
    <LegalSection number="06" title="Datos y confidencialidad"><p>Cada organización conserva la titularidad y responsabilidad sobre sus datos. El Proveedor aplicará las medidas descriptas en la Política de Privacidad, los anexos de tratamiento y el contrato aplicable. Las partes protegerán la información confidencial y la utilizarán exclusivamente para ejecutar el servicio, salvo obligación legal.</p></LegalSection>
    <LegalSection number="07" title="Propiedad intelectual"><p>El software, diseño, documentación, modelos, marcas y componentes propios de EcoNexo pertenecen al Proveedor o a sus licenciantes. El uso no transfiere propiedad intelectual. Los componentes de código abierto mantienen sus licencias respectivas. Las fuentes externas se rigen por sus términos, atribuciones y límites de disponibilidad.</p></LegalSection>
    <LegalSection number="08" title="Disponibilidad e integraciones"><p>El Proveedor procurará continuidad y recuperación razonables, sin garantizar funcionamiento ininterrumpido. Pueden existir demoras, datos incompletos o interrupciones por conectividad, satélites, sensores, clima, proveedores, mantenimiento o fuerza mayor. Los niveles de servicio, soporte, respaldo y continuidad deberán definirse en el contrato comercial.</p></LegalSection>
    <LegalSection number="09" title="Planes, pagos y cambios"><p>Precios, impuestos, moneda, ajustes, plazos, renovaciones y cancelaciones se establecerán en la propuesta u orden de servicio. Las versiones de prueba pueden limitar funciones y datos. Las modificaciones materiales de estos términos serán notificadas por medios razonables y aplicarán hacia adelante, respetando contratos vigentes y normas imperativas.</p></LegalSection>
    <LegalSection number="10" title="Suspensión y terminación"><p>El acceso puede suspenderse ante riesgo de seguridad, incumplimiento, uso ilegal, falta de pago o requerimiento de autoridad competente. Cuando sea razonable, se notificará y permitirá subsanar. Al terminar, se aplicará el procedimiento de exportación, devolución y eliminación acordado, sujeto a retenciones legales y respaldos controlados.</p></LegalSection>
    <LegalSection number="11" title="Responsabilidad"><p>En la máxima medida permitida por la ley, las decisiones operativas permanecen bajo responsabilidad de la organización y sus autoridades. Las limitaciones económicas, exclusiones, indemnidades y seguros aplicables deben acordarse en el contrato comercial; no se excluyen responsabilidades que legalmente no puedan limitarse, incluidos dolo, culpa grave o derechos inderogables.</p></LegalSection>
    <LegalSection number="12" title="Ley y contacto"><p>La ley, jurisdicción y mecanismo de resolución de controversias se completarán en la Provincia de Misiones, salvo acuerdo válido distinto, según el domicilio del Proveedor y el tipo de cliente, respetando las normas argentinas imperativas. Consultas: <strong>{legalContact}</strong>.</p></LegalSection>
  </LegalPage>;
}
