import { LegalPage, LegalSection, legalContact } from "../../components/LegalPage";

export default function SecurityPage() {
  return <LegalPage title="Seguridad y Divulgación Responsable" subtitle="Controles técnicos, límites y canal propuesto para reportar vulnerabilidades.">
    <LegalSection number="01" title="Arquitectura de confianza"><p>EcoNexo separa datos por organización en cada consulta, aplica roles, tokens de acceso con vencimiento y credenciales internas entre servicios. Los secretos se inyectan por entorno y el arranque productivo rechaza valores de ejemplo.</p></LegalSection>
    <LegalSection number="02" title="Protección de datos"><ul><li>TLS obligatorio en producción y encabezados de seguridad.</li><li>Contraseñas con Argon2id y verificación de Google del lado servidor.</li><li>Bucket privado para evidencias, cifrado en reposo y URLs firmadas temporales.</li><li>Validación de firma, tipo y tamaño de archivos; límites de solicitudes en endpoints públicos.</li><li>Tokens públicos de informes de alta entropía almacenados sólo como hash y revocables.</li><li>Auditoría de publicaciones y plan de trazabilidad ampliable.</li></ul></LegalSection>
    <LegalSection number="03" title="Operación segura"><p>Antes de producción deben habilitarse un WAF o gateway con límites distribuidos, gestor de secretos, rotación, escaneo de dependencias e imágenes, pruebas de recuperación, monitoreo, alertas, copias cifradas, inventario de activos, revisión de permisos y pruebas de penetración independientes.</p></LegalSection>
    <LegalSection number="04" title="Divulgación responsable"><p>Las vulnerabilidades deben informarse de forma privada a <strong>{legalContact}</strong>, incluyendo activo, pasos de reproducción, impacto y evidencia mínima. No deben accederse datos ajenos, degradarse servicios, realizarse ingeniería social ni publicarse detalles antes de acordar una corrección. El programa de recompensas, plazos y puerto seguro deberán formalizarse antes del lanzamiento.</p></LegalSection>
    <LegalSection number="05" title="Incidentes"><p>El proceso propuesto contempla clasificación, contención, preservación de evidencia, erradicación, recuperación, análisis causal y notificación a clientes, personas y autoridades cuando corresponda. Los responsables, tiempos y canales se documentarán en el plan de respuesta y los contratos.</p></LegalSection>
  </LegalPage>;
}
